config/routes.rb
Shopoo::Application.routes.draw do

  get "main/about"
  get "main/contact"
  match '/admin', :to => 'main#admin'

  resources :sessions, :only => [:new, :create, :destroy]
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/signup', :to => 'users#new'
  match '/profile/:id/edit', :to => 'users#edit', :as => 'edit_profile'
  match '/profile/:id', :to => 'users#show', :as => 'profile'
  match '/profile/:id/billing', :to => 'users#billing', :as => 'billing'
  match '/orders/:id', :to => 'users#orders', :as => 'orders'
  put 'users/update_billing'
  match '/cart/update_quantity', :to => 'items#update_quantity', :as => 'update_quantity'
  match '/cart/add_promo', :to => 'items#add_promo', :as => 'add_promo'
  match '/checkout', :to => 'items#checkout'
  match '/finalize_checkout', :to => 'items#finalize_checkout'
  match '/reports', :to => 'items#reports', :as => 'reports'
  resources :users
  resources :items
  resources :promos
  match '/allpromos', :to => 'promos#browse'
  match '/new', :to => 'items#new'
  match '/browse', :to => 'items#browse'
  match '/add_item', :to => 'users#add_item'
  match '/cart', :to => 'items#cart'
  match '/remove_item', :to => 'users#remove_item'
  match '/view/:name/:id', :to => 'items#view', :as => 'view'
  root :to => 'main#home'

end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def home
    @title = "ShopOO"
    @items = Item.paginate(:page => params[:page],
                                        :per_page => 8)
  end

  def about
  end

  def contact
  end

  def admin
    if !current_user.admin?
      redirect_to root_path
    end
    @user = current_user
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/about.html.erb
<h1>Main#about</h1>
<p>Find me in app/views/main/about.html.erb</p>

app/views/main/admin.html.erb
<div class="centered">
  <h1>Administrator Options</h1>
</div>


<table>
  <tr>
    <td style="width:300px">
      <div>
        <%= gravatar_for @user, :size=>200 %>  <br/>
        Welcome back <%= @user.firstname %>!
      </div>
    </td>
    <td style="font-size: large">
      <ul>
        <li>
          <%= link_to "Reports", reports_path %> <br/>
        </li>
        <li>
          <%= link_to "Add New Item", new_item_path %> <br/>
        </li>
        <li>
          <%= link_to "Add New Promo", new_promo_path %> <br/>
        </li>
        </li>
        <li>
          <%= link_to "View Promos", allpromos_path %> <br/>
        </li>
        <li>
          <%= link_to "View/Delete Users", users_path %> <br/>
        </li>
      </ul>
    </td>
  </tr>
</table>

app/views/main/contact.html.erb
<h1>Main#contact</h1>
<p>Find me in app/views/main/contact.html.erb</p>

app/views/main/home.html.erb
<%= render 'layouts/slider' %>
<header class="featured">Featured Items</header>
<%= will_paginate @items %>
<div class="items">
  <% @items.each do |item| %>
    <div class="item-container">
      <div class="item">
        <%=link_to( image_tag( item.url ), view_path(item.name, item.id)) %>
        <p><%= item.name %></p>
        <p><span class="price"><%= "$#{item.cost}"%></span>
        <% if signed_in? %>
            <%= link_to "Add to Cart", :controller => "users", :action => "add_item", :id => item.id, :quantity => 1 %>
        <% end %>
        </p>
      </div>
    </div>
  <% end %>
</div>