config/routes.rb
Shopoo::Application.routes.draw do

  get "main/about"
  get "main/contact"
  match '/admin', :to => 'main#admin'

  resources :sessions, :only => [:new, :create, :destroy]
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/signup', :to => 'users#new'
  match '/profile/:id/edit', :to => 'users#edit', :as => 'edit_profile'
  match '/profile/:id', :to => 'users#show', :as => 'profile'
  match '/profile/:id/billing', :to => 'users#billing', :as => 'billing'
  match '/orders/:id', :to => 'users#orders', :as => 'orders'
  put 'users/update_billing'
  match '/cart/update_quantity', :to => 'items#update_quantity', :as => 'update_quantity'
  match '/cart/add_promo', :to => 'items#add_promo', :as => 'add_promo'
  match '/checkout', :to => 'items#checkout'
  match '/finalize_checkout', :to => 'items#finalize_checkout'
  match '/reports', :to => 'items#reports', :as => 'reports'
  resources :users
  resources :items
  resources :promos
  match '/allpromos', :to => 'promos#browse'
  match '/new', :to => 'items#new'
  match '/browse', :to => 'items#browse'
  match '/add_item', :to => 'users#add_item'
  match '/cart', :to => 'items#cart'
  match '/remove_item', :to => 'users#remove_item'
  match '/view/:name/:id', :to => 'items#view', :as => 'view'
  root :to => 'main#home'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer          not null, primary key
#  firstname          :string(255)
#  lastname           :string(255)
#  encrypted_password :string(255)
#  email              :string(255)
#  billing_info_id    :integer
#  address_id         :integer
#  cart_id            :integer
#  admin              :boolean
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  salt               :string(255)
#

require 'digest'

class User < ActiveRecord::Base
  # virtual attribute - not in database. It only exists in memory until encrypted
  attr_accessor :password
  attr_accessible :email, :firstname, :lastname, :password, :password_confirmation, :address_attributes
  belongs_to :billing_info
  belongs_to :address
  has_many :carts
  accepts_nested_attributes_for :address

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :firstname, :presence    => true,
                        :length      => { :maximum => 50 }
  validates :lastname,  :presence    => true,
                        :length      => { :maximum => 50 }
  validates :email,     :presence    => true,
                        :format      => { :with => email_regex },
                        :uniqueness  => { :case_sensitive => false }
  validates :password,  :presence    => true,
                        :confirmation => true,
                        :length      => { :within => 6..40 }

  # active record will call this before saving the model
  before_save :encrypt_password

  # returns true if the user's password is the same as the one submitted
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  def cart
    return Cart.find_by_user_id_and_order_date(self.id,nil)
  end

  def checkout
    #Gets the old cart and checks it out
    @oc = cart
    @oc.checkout
    #Creates a new empty cart for the user
    @c = Cart.new
    @c.user = self
    @c.save
  end

  def orders
    return Cart.find_all_by_user_id(self.id, :conditions => ["order_date IS NOT NULL"])
  end

  #make all methods below private
  private

    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:edit, :update, :index, :destroy]
  before_filter :admin_user,   :only => :destroy

  def index
    @title = "Registered Users"
    @users = User.paginate(:page => params[:page],
                           :per_page => 10)
  end

  def orders
    @title = "View Orders"
    @user = User.find(params[:id])
    @orders = @user.orders.paginate(:page => params[:page], :per_page => 1)
  end

  def new
    @title = "Sign Up"
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @cart = Cart.new
    @shipping_address = Address.new
    @billing_address = Address.new
    @billing_info = BillingInfo.new

    if @user.save
      @cart.save
      @shipping_address.save
      @billing_address.save
      @billing_info.save
      @cart.update_attribute :user_id, @user.id
      @user.update_attribute :address_id, @shipping_address.id
      @user.update_attribute :billing_info_id, @billing_info.id
      @billing_info.update_attribute :address_id, @billing_address.id

      sign_in @user
      flash[:success] = "Welcome to ShopOO!"
      redirect_to profile_path(@user)
    else
      @title = "Sign Up"
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @title = "#{@user.firstname} #{@user.lastname}"
  end

  def edit
    @title = "Edit Profile"
    @user = User.find(params[:id])
    @address = Address.find(@user.address_id)
  end

  def billing
    @title = "Edit Billing"
    @user = User.find(params[:id])
    @billing_info = @user.billing_info
    @billing_address = @billing_info.address
  end

  def update_billing
    @user = current_user
    @billing_info = @user.billing_info

    card = params[:billing_info][:cardnumber]
    isValidCard = card.creditcard?(card.creditcard_type.downcase)

    if isValidCard && @billing_info.update_attributes(params[:billing_info])
      @billing_info.build_address
      flash[:success] = "Profile updated."
      redirect_to profile_path(@user)
    else
      @title = "Edit Billing"
      redirect_to billing_path(@user), :notice => "Invalid Card"
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      @user.build_address
      flash[:success] = "Profile updated."
      redirect_to profile_path
    else
      @title = "Edit User"
      render 'edit'
    end
  end

  def add_item
    @itemid = params[:id]
    @quantity = params[:quantity]
    @user = current_user
    @cart = @user.cart
    if @cart.add_item(@itemid,@quantity)
      flash[:success] = "Item added."
    else
      flash[:error] = "Item is already in cart."
    end
    redirect_to '/cart'
  end

  def remove_item
    @itemid = params[:id]
    @user = current_user
    @cart = @user.cart
    @cart.remove_item(@itemid)
    flash[:success] = "#{Item.find(@itemid).name} removed."
    redirect_to '/cart'
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_path
  end


  private

    def authenticate
      deny_access unless signed_in?
    end

    def admin_user
      redirect_to root_path unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { :size => 100})
    gravatar_image_tag(user.email.downcase, :alt => user.firstname,
                                            :class => 'gravatar',
                                            :gravatar => options)
  end

end

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user %>
  <%= link_to "#{user.firstname} #{user.lastname}", profile_path(user) %>
  <% if current_user.admin? %>
    | <%= link_to "delete", user, :method => :delete, :confirm => "Are you sure?",
                                :title => "Delete #{user.firstname} #{user.lastname}" %>
  <% end %>
</li>

app/views/users/billing.html.erb
<div style="text-align: center">
  <h1>Edit Billing Information</h1>
</div>
<div style="float:left; margin-left: 100px">
<%= form_for @billing_info, :url => url_for(:controller => 'users', :action => 'update_billing') do |f| %>
    <%= render 'shared/errors' %>
    <div class="field">
      <%= f.label :cardtype, "Card Type"%><br/>
      <%= f.select :cardtype, [['Visa','Visa'],['American Express','American_Express'],['Discover','Discover'], ['Mastercard','Mastercard']] %>
    </div>
    <div class="field">
      <%= f.label :cardnumber, "Card Number"%><br/>
      <%= f.text_field :cardnumber %>
    </div>
    <div class="field">
      <%= f.label :cardname, "Name as appears on card" %><br/>
      <%= f.text_field :cardname %>
    </div>
    <div class="field">
      <%= f.label :expiration %><br/>
      <%= f.text_field :expiration %>
    </div>
    <div class="field">
      <%= f.label :securitycode, "Security Code" %><br/>
      <%= f.text_field :securitycode %>
    </div>
    <%= f.fields_for :address do |a| %>
        <div class="field">
          <%= a.label :streetaddress, "Street"%><br/>
          <%= a.text_field :streetaddress %>
        </div>
        <div class="field">
          <%= a.label :streetaddress2, "Street 2" %><br/>
          <%= a.text_field :streetaddress2 %>
        </div>
        <div class="field">
          <%= a.label :city %><br/>
          <%= a.text_field :city %>
        </div>
        <div class="field">
          <%= a.label :state %><br/>
          <%= a.text_field :state %>
        </div>
        <div class="field">
          <%= a.label :zip %><br/>
          <%= a.text_field :zip %>
        </div>
    <% end %>
    <div class="actions">
      <%= f.submit "Update" %>
    </div>
<% end %>
</div>
<div style="float:right; margin-right:200px; margin-top: 50px">
  <%= gravatar_for @user, :size=>200 %>  <br/>
  <a href="http://gravatar.com/emails">Change Your Gravatar!</a>
  <br/><br/> <br/> <br/>
  <%= link_to ">> Edit profile and shipping", edit_profile_path(@user)%>
</div>

app/views/users/edit.html.erb
<div style="text-align: center">
  <h1>Edit Profile and Shipping Information</h1>
</div>


<div style="float:left; margin-left:100px">
<%= form_for(@user) do |f| %>
    <%= render 'shared/errors' %>
    <div class="field">
      <%= f.label :firstname, "First Name"%><br/>
      <%= f.text_field :firstname %>
    </div>
    <div class="field">
      <%= f.label :lastname, "Last Name" %><br/>
      <%= f.text_field :lastname %>
    </div>
    <div class="field">
      <%= f.label :email %><br/>
      <%= f.text_field :email %>
    </div>
    <%= f.fields_for :address do |a| %>
        <div class="field">
          <%= a.label :streetaddress, "Street"%><br/>
          <%= a.text_field :streetaddress %>
        </div>
        <div class="field">
          <%= a.label :streetaddress2, "Street 2" %><br/>
          <%= a.text_field :streetaddress2 %>
        </div>
        <div class="field">
          <%= a.label :city %><br/>
          <%= a.text_field :city %>
        </div>
        <div class="field">
          <%= a.label :state %><br/>
          <%= a.text_field :state %>
        </div>
        <div class="field">
          <%= a.label :zip %><br/>
          <%= a.text_field :zip %>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :password %><br/>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation, "Confirmation" %><br/>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions">
      <%= f.submit "Update" %>
    </div>
<% end %>
</div>
<div style="float:right; margin-right:200px; margin-top: 50px">
    <%= gravatar_for @user, :size=>200 %>  <br/>
    <a href="http://gravatar.com/emails">Change Your Gravatar!</a>
    <br/><br/> <br/> <br/>
    <%= link_to ">> Edit Billing", billing_path(@user)%>
</div>

app/views/users/index.html.erb
<h1>All Users</h1>

<%= will_paginate %>

<ul class="users">
    <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
    <%= render 'shared/errors' %>
    <div class="field">
      <%= f.label :firstname, "First Name"%><br/>
      <%= f.text_field :firstname %>
    </div>
    <div class="field">
      <%= f.label :lastname, "Last Name" %><br/>
      <%= f.text_field :lastname %>
    </div>
    <div class="field">
      <%= f.label :email %><br/>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %><br/>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation, "Confirmation" %><br/>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions">
      <%= f.submit "Sign Up" %>
    </div>
<% end %>

app/views/users/orders.html.erb
<div style="text-align: center">
  <h1>View Orders</h1>
</div>

<% @orders.each do |order| %>
    <p style="font-size:x-large">Total: <span style="color:red"><%= "$#{number_with_precision(order.get_total_and_tax, :precision => 2)}" %></span></p>
    <p style="font-size:x-large; margin-top:-40px">Tax: <%= "$#{number_with_precision(order.get_tax, :precision => 2)}" %></p>
    <p style="font-size:x-large; margin-top:-40px">Date Ordered: <span style="color:red"><%= order.order_date %></span><br/></p>
  <div class="items">
    <% order.items.each do |item| %>
      <div class="item-container">
        <div class="item centered">
          <%=link_to( image_tag( item.url ), "#") %>
          <%= item.name %>
          <br/>
          <%= "Quantity: #{order.get_item_quantity(item.id)}" %>
          <br/>
          <p><span class="price"><%= "Unit Price: $#{item.cost}"%></span>
        </div>
      </div>
    <% end %>
    <br class="clear"/>

    <% if order.promos.size > 0 %>
    <h1>Promos</h1>
    <% order.promos.each do |promo| %>
        <div class="item-container">
          <div class="promo">
            <p><b><%= "#{promo.code}"  %></b></p>
            <% if promo.item == nil %>
                <p><%="Cart discount: #{promo.discount*100}%" %></p>
            <% else %>
                <p><%= promo.item.name %> - <%= "Discount: #{promo.discount*100}%" %></p>
            <% end %>
            <p><%= if promo.expiration.nil? then "Never expires" else "Expires on #{promo.expiration}" end %></p>
          </div>
        </div>
    <% end %>
    <% end %>
    <br class="clear"/>
</div>
<% end %>
<%= will_paginate @orders %>

app/views/users/show.html.erb
<table class="profile" summary="Profile Information">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user, :size=>150 %>
        <%= "#{@user.firstname} #{@user.lastname}" %>
      </h1>
    </td>
    <td class="sidebar round">
      <strong>Name</strong><%= " #{@user.firstname} #{@user.lastname}" %><br/>
      <strong>URL</strong> <%= link_to user_path(@user), @user %><br/><br/><br/><br/><br/>
      <% if current_user?(@user) || current_user.admin? %>
          <%= link_to "View Orders" , orders_path(@user) %>
          <br/>
          <%= link_to "Edit Profile", edit_profile_path(@user) %>
          <br/>
          <%= link_to "Edit Billing", billing_path(@user) %>
          <br/>
      <% end %>
      <% if current_user.admin? %>
        <%= link_to "Admin Options", "/admin" %>
      <% end %>
    </td>
  </tr>
</table>