config/routes.rb
Shopoo::Application.routes.draw do

  get "main/about"
  get "main/contact"
  match '/admin', :to => 'main#admin'

  resources :sessions, :only => [:new, :create, :destroy]
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/signup', :to => 'users#new'
  match '/profile/:id/edit', :to => 'users#edit', :as => 'edit_profile'
  match '/profile/:id', :to => 'users#show', :as => 'profile'
  match '/profile/:id/billing', :to => 'users#billing', :as => 'billing'
  match '/orders/:id', :to => 'users#orders', :as => 'orders'
  put 'users/update_billing'
  match '/cart/update_quantity', :to => 'items#update_quantity', :as => 'update_quantity'
  match '/cart/add_promo', :to => 'items#add_promo', :as => 'add_promo'
  match '/checkout', :to => 'items#checkout'
  match '/finalize_checkout', :to => 'items#finalize_checkout'
  match '/reports', :to => 'items#reports', :as => 'reports'
  resources :users
  resources :items
  resources :promos
  match '/allpromos', :to => 'promos#browse'
  match '/new', :to => 'items#new'
  match '/browse', :to => 'items#browse'
  match '/add_item', :to => 'users#add_item'
  match '/cart', :to => 'items#cart'
  match '/remove_item', :to => 'users#remove_item'
  match '/view/:name/:id', :to => 'items#view', :as => 'view'
  root :to => 'main#home'

end

app/views/layouts/_footer.html.erb
<footer class="round">
  <div id="footer-left" class="left">
    <h1>Company</h1>
    <ul>
      <li>About</li>
      <li>Contact</li>
      <li>Privacy Policy</li>
      <li>Terms & Conditions</li>
    </ul>
    </p>
  </div>
  <div id="footer-right" class="right">
    <h1>FAQ</h1>
    <ul>
      <li>About</li>
      <li>Contact</li>
    </ul>
  </div>
  <div id="footer-middle" class="centered">
    <h1>Information</h1>
    <ul>
      <li>Products</li>
      <li>Features</li>
    </ul>
  </div>
  <div style="clear: both"></div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div id="search">
    <% #Search Container which holds search bar and advanced search %>
    <div class="search-container">
        <%= form_tag(:action=>"browse", :controller=>"items") do %>
          <%= text_field_tag :query, params[:query], :class=>'field' %>
          <%= submit_tag '', :class=>"submit-button" %>
        <% end %>
      <div style="clear:both"></div>
    </div>
  </div>
  <div style="clear:both"></div>

  <% #Site Logo %>
  <h1 id="logo"><a title="Home" href="/">ShopOO</a></h1>

  <% #Account options such as My Account, Shopping Cart, and Checkout%>
  <div id="account-options">
    <ul>
      <% if signed_in? %>
          <li><%= "#{pluralize(current_user.cart.items.count, "item")} in cart" %></li>
      <% else %>
          <li>Not signed in</li>
      <% end %>
      <% if signed_in? %>
        <li><%= link_to profile_path(current_user), :class => "account round" do %><span></span>My Account<% end %></li>
      <% else %>
        <li><%= link_to signin_path, :class => "signin round" do %><span></span>Sign in<% end %></li>
      <% end %>
      <% if signed_in? %>
          <li><%= link_to signout_path, :class => "signout round" do %><span></span>Sign out<% end %></li>
      <% end %>
      <li><%= link_to "/cart", :class => "cart round" do %><span></span>Shopping Cart<% end %></li>
      <li><%= link_to "/checkout", :class => "checkout round" do %><span></span>Checkout<% end %></li>
    </ul>
  </div>
  <div style="clear:both"></div>
</header>

app/views/layouts/_navigation.html.erb
<div id="navigation-bar" class="round">
  <ul>
    <li><a href="/">Home</a></li>
    <li><%= link_to "Playstation 3", {:action=>"browse", :controller=>"items", :category=>"ps3"} %></li>
    <li><%= link_to "Xbox 360", {:action=>"browse", :controller=>"items", :category=>"xbox360"} %></li>
    <li><%= link_to "PC", {:action=>"browse", :controller=>"items", :category=>"pc"} %></li>
    <li><%= link_to "Wii U", {:action=>"browse", :controller=>"items", :category=>"wiiu"} %></li>
    <li><%= link_to "Nintendo 3DS", {:action=>"browse", :controller=>"items", :category=>"3ds"} %></li>
    <li><%= link_to "PS Vita", {:action=>"browse", :controller=>"items", :category=>"vita"} %></li>
  </ul>
  <div style="clear:both"></div>
</div>

app/views/layouts/_slider.html.erb
<!--  Outer wrapper for presentation only, this can be anything you like -->
<div id="banner-fade">

  <!-- start Basic Jquery Slider -->
  <ul class="bjqs round">
    <li><img src="/assets/ps3banner.jpg" title="Automatically generated caption"></li>
    <li><img src="/assets/xbox_slim_banner.jpg" title="Automatically generated caption"></li>
    <li><img src="/assets/nintendo-banner.jpg" title="Automatically generated caption"></li>
    <li><img src="/assets/gaming-computers.jpg" title="Automatically generated caption"></li>
  </ul>
  <!-- end Basic jQuery Slider -->

</div>
<!-- End outer wrapper -->

<script class="secret-source">
    jQuery(document).ready(function($) {

        $('#banner-fade').bjqs({
            height      : 320,
            width       : 922,
            responsive  : true
        });

    });
</script>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!--[if lt IE 8]>
<%= stylesheet_link_tag 'blueprint/ie'%>
<![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>
<%= stylesheet_link_tag 'bjqs', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= render 'layouts/stylesheets' %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag "http://code.jquery.com/jquery-1.7.1.min.js" %>
  <%= javascript_include_tag "bjqs-1.3.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= render 'layouts/header' %>
  <%= render 'layouts/navigation' %>
  <section class="round">
    <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %> </div>
    <% end %>
    <%= yield %>
  </section>
  <div style="clear:both"></div>
  <%= render 'layouts/footer' %>
</div>
</body>
</html>